import { z } from 'genkit';
import { ai } from '../ai'
import { ScenarioSchema } from '../schemas';
import fs from 'node:fs';

const SYSTEM_PROMPT = `
あなたは論理的かつ創造的な脚本家・演出家チームです。
ユーザーの「テーマ」から、Remotion動画のための「構成データ(JSON)」を作成してください。

### 重要指針
1. **Nanobanana画像生成**: asset_prompts.images には、各シーンを象徴する高精度な画像生成プロンプト（英語）を複数（3-5個）含めてください。
2. **Kinetic Typography**: 各シーンの text_primary と text_secondary は、GSAPでアニメーションさせることを前提に、印象的で短いフレーズにしてください。
3. **架空の名称禁止**: 指定されたリスト（EFFECTS, TRANSITIONS, COLOR_THEMES）の中にあるものだけを選択してください。
`;

export const brainstormScenarioFlow = ai.defineFlow(
  {
    name: 'brainstormScenario',
    inputSchema: z.string().describe('ユーザーが指定する動画のテーマ'),
    outputSchema: ScenarioSchema,
  },
  async (theme) => {
    console.log(`\n🧠 [Genkit Brain] Activated. Theme: "${theme}"`);
    console.log('✍️ Drafting scenario...');

    const { output } = await ai.generate({
      // ユーザーの指示に従い最新のプレビューモデルを使用
      model: 'googleai/gemini-3-flash-preview',
      system: SYSTEM_PROMPT,
      prompt: `テーマ: ${theme}`,
      output: { schema: ScenarioSchema },
    });

    if (!output) {
      throw new Error('シナリオの生成に失敗しました。');
    }

    // 古いスクリプトで行っていたフレーム数の自動計算・付与
    let currentFrame = 0;
    const timelineWithFrames = output.timeline.map((scene, i) => {
      const duration = scene.duration_frames || 150;
      const updatedScene = {
        ...scene,
        id: i + 1, // 1-indexed
        start_frame: currentFrame,
        end_frame: currentFrame + duration,
      };
      currentFrame += duration;
      return updatedScene;
    });

    const finalOutput = {
      ...output,
      timeline: timelineWithFrames,
    };

    // テストや後続パイプラインのためにファイルにも出力しておく
    const OUTPUT_FILE = 'src/ai_scenario.json';
    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(finalOutput, null, 2));

    console.log(`\n✅ Scenario Generated by Genkit!`);
    console.log(`📂 Saved to: ${OUTPUT_FILE}`);

    return finalOutput;
  }
);
