import { z } from 'zod';

export const EffectStackConfigSchema = z.object({
  src: z.string(),
  opacity: z.number().optional().default(0.65),
  blendMode: z.string().optional().default('screen'),
  zIndex: z.number().optional().default(10),
  muted: z.boolean().optional().default(true),
});

export const BattleSpiritThemeSchema = z.object({
  themeColor: z.string(),
  glowColor: z.string(),
  particleColor1: z.string(),
  particleColor2: z.string(),
  music: z.object({
    src: z.string(),
    startFrom: z.number().optional().default(0),
    volume: z.number().optional().default(1),
    bpm: z.number().optional().default(120),
  }),
  opponent: z.object({
    name: z.string(),
    image: z.string(),
    borderColor: z.string(),
    glowColor: z.string(),
  }),
  liver: z.object({
    name: z.string(),
    image: z.string(),
    altImage: z.string().optional().default(''),
    altImageStartFrame: z.number().optional().default(0),
    altImageEndFrame: z.number().optional().default(0),
    gridImage: z.string().optional().default(''), // 16分割用画像（指定がない場合はimageを使用）
    borderColor: z.string(),
    glowColor: z.string(),
  }),
  endingText: z.string(),
  customVsVideo: z.string().optional().default(''),
  features: z.object({
    useGlitch: z.boolean(),
    useMirror: z.boolean(),
    useDoublingGrid: z.boolean(),
    useGridConvergence: z.boolean().optional().default(false),
    useSnowEffect: z.boolean().optional().default(false),
    useKaleidoscope: z.boolean().optional().default(false),
    useSpinIntro: z.boolean().optional().default(false),
    useCircleLiver: z.boolean().optional().default(false),
    useMetallicVs: z.boolean().optional().default(false),
    hideVsFocusLines: z.boolean().optional().default(false),
    colorizeVsVideo: z.boolean().optional().default(false),
    useSakuraEffect: z.boolean().optional().default(false),
    hideDefaultParticles: z.boolean().optional().default(false),
  }),
  lightLeakColor: z.string().optional().default(''),
  liverIntroDuration: z.number().optional().default(120),
  customDurations: z.object({
    opening: z.number().optional().default(180),
    date: z.number().optional().default(150),
    liverIntro: z.number().optional().default(210),
    msg: z.number().optional().default(0),
    opponent: z.number().optional().default(105),
    vs: z.number().optional().default(90),
    rule: z.number().optional().default(120),
    ending: z.number().optional().default(120),
    logo: z.number().optional().default(60),
  }).optional().default({ opening: 180, date: 150, liverIntro: 210, msg: 0, opponent: 105, vs: 90, rule: 120, ending: 120, logo: 60 }),
  openingText: z.array(z.string()).optional().default([]),
  rulesText: z.array(z.string()).optional().default([]),
  dateText: z.array(z.string()).optional().default([]),
  textStroke: z.string().optional().default(''),
  textAnimation: z.enum(['kinetic', 'fade']).optional().default('kinetic'),
  reverseVsOrder: z.boolean().optional().default(false),
  customBackground: z.string().optional().default(''),
  opponentBackground: z.string().optional().default(''),
  sceneLiverEffect: EffectStackConfigSchema.optional().default({ src: '', opacity: 0, blendMode: 'screen', zIndex: 10, muted: true }),
  sceneVsEffect: EffectStackConfigSchema.optional().default({ src: '', opacity: 0, blendMode: 'screen', zIndex: 10, muted: true }),
  fontFamily: z.string().optional().default(''),
});

export type BattleSpiritTheme = z.infer<typeof BattleSpiritThemeSchema>;
