import React from 'react';
import {
  AbsoluteFill,
  Audio,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';
import { useAudioData, visualizeAudio } from '@remotion/media-utils';
import { Lyrics } from './Lyrics';
import { ChorusLyrics } from './ChorusLyrics';
// import { SkiaChorusLyrics } from './SkiaChorusLyrics';
import { CharacterScenes } from './CharacterScenes';
import { SpeedLines } from '../../components/overlays/SpeedLines';
import { BackgroundScenes } from './BackgroundScenes';
import { SpeedSlash } from './SpeedSlash';
import { TIMELINE } from './timeline';
// subtitles.json will be generated by the script, import it directly
// If it doesn't exist initially, it might cause issue, but we created a dummy one.
import subtitles from './subtitles.json';

// Background logic now handled in BackgroundScenes.tsx

// 映画風の黒帯 (シネマスコープ)
const CinemaScope: React.FC = () => {
  return (
    <AbsoluteFill style={{ pointerEvents: 'none', zIndex: 1000 }}>
      <div
        style={{
          position: 'absolute',
          top: 0,
          width: '100%',
          height: '10%',
          background: 'black',
        }}
      />
      <div
        style={{
          position: 'absolute',
          bottom: 0,
          width: '100%',
          height: '10%',
          background: 'black',
        }}
      />
    </AbsoluteFill>
  );
};

export const KimitonaraComposition: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const time = frame / fps;
  const music = staticFile('assets/audio/music/君となら.mp3');
  const audioData = useAudioData(music);

  // If no audio data, beat is 0
  if (!audioData) {
    return null; // Or return loading state
  }

  // Audio Analysis for Reactivity
  const visualization = visualizeAudio({
    fps,
    frame,
    audioData,
    numberOfSamples: 16, // Low for performance, enough for bass/treble
  });

  // Simple bass detection (low frequencies)
  const bass = visualization.slice(0, 4).reduce((a, b) => a + b, 0) / 4;

  const currentSection = TIMELINE.find(
    (section) => time >= section.start && time < section.end,
  );
  const showSpeedLines = currentSection?.showSpeedLines ?? false;
  const showSpeedSlash = currentSection?.showSpeedSlash ?? false;

  return (
    <AbsoluteFill>
      {/* Dynamic Background Manager */}
      <BackgroundScenes beat={bass} />

      {/* 歌詞アニメーション (背景レイヤー) */}
      <Lyrics subtitles={subtitles} layer="background" />

      {/* Ado-Style Speed Lines (Global FX controlled by Timeline) */}
      {showSpeedLines && <SpeedLines />}

      {/* Back Chorus Lyrics (Parallax: Slower, Behind Character) */}
      <ChorusLyrics subtitles={subtitles} layer="back" />

      {/* Character (Nova) - now using nova-chracter.png */}
      <CharacterScenes />

      {/* Ado-style Speed Slash (Purple Strip) - Between Character and Front Lyrics */}
      {showSpeedSlash && <SpeedSlash />}

      {/* 歌詞アニメーション (前景レイヤー: ここは汎用歌詞) */}
      <Lyrics subtitles={subtitles} layer="foreground" />

      {/* Front Chorus Lyrics (Parallax: Faster, In Front of Character) */}
      <ChorusLyrics subtitles={subtitles} layer="front" />

      <Audio src={music} />

      {/* 映画風の黒帯 */}
      <CinemaScope />
    </AbsoluteFill>
  );
};
