import fs from 'node:fs';
import dotenv from 'dotenv';
import { GoogleGenerativeAI } from '@google/generative-ai';

dotenv.config();

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

if (!GEMINI_API_KEY) {
  console.error('❌ Error: GEMINI_API_KEY is not set in .env');
  console.error('👉 Please get your API key from https://aistudio.google.com/');
  process.exit(1);
}
const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: 'gemini-3-flash-preview' }); // ⚠️ Use ONLY gemini-3 or newer. gemini-1.5 is deprecated for this project.

// --- Constants ---

const EFFECTS = [
  'zoom_and_glitch',
  'split_vertical_slide',
  'camera_shake_with_particles',
  'awakening_flash',
  'dim_and_focus',
];

const TRANSITIONS = [
  'SeismicImpactSlam',
  'HyperdriveSingularity',
  'NeuralGlitchOverload',
  'VortexShredder',
  'SolarProminenceBurst',
  'AbyssGravityFall',
  'DimensionalRiftTear',
  'CyberPuncture',
  'KineticCrashBounce',
  'TectonicPlateShift',
  'PrismShatterBlast',
  'QuantumPhaseDisruption',
  'DataVoidInferno',
  'MagmaticMeltdown',
  'CircularReveal',
  'CubeTransition',
  'FlipTransition',
  'GlitchTransition',
  'ZoomBlurTransition',
  'HyperSpinTransition',
  'Wipe',
  'CrossDissolve',
  'FlashTransition',
];

const SYSTEM_PROMPT = `
あなたは論理的かつ創造的な脚本家・演出家チームです。
ユーザーの「テーマ」から、Remotion動画のための「構成データ(JSON)」を作成してください。

以下の「利用可能なエフェクト」と「トランジション」のリストから最適なものを選択してください。
架空のエフェクト名は使用禁止です。

【利用可能なエフェクト (effects)】:
${EFFECTS.join(', ')}

【利用可能なトランジション (transitions)】:
${TRANSITIONS.join(', ')}

JSONの出力フォーマットは厳密に以下を守ってください。Markdown記法は含めないでください。
JSON構造:
{
  "title": "タイトル",
  "concept": "作品のコンセプト解説",
  "timeline": [
    {
      "id": 1,
      "label": "scene_name",
      "effect": "エフェクト名",
      "transition": "トランジション名（場面転換時に使用。最後のシーンは不要）",
      "text_primary": "表示テキスト",
      "text_secondary": "サブテキスト",
      "color_theme": "neon_blue" | "vibrant_magenta" | "fire_and_ice" | "electric_gold" | "monochrome_highlight",
      "duration_frames": 150
    }
  ],
  "asset_prompts": {
    "music": "Music generation prompt (English)",
    "sfx": "SFX generation prompt (English)",
    "video": "Visual style description (English)",
    "voice": "Narration text (Japanese)"
  }
}
`;

async function main() {
  const userTheme = process.argv[2];
  if (!userTheme) {
    console.error(
      '❌ Usage: npx tsx scripts/brainstorm_scenario_gemini.ts <theme>',
    );
    process.exit(1);
  }

  console.log(`\n🧠 [Gemini Brain] Activated. Theme: "${userTheme}"`);
  console.log('✍️ Drafting scenario...');

  try {
    const result = await model.generateContent([
      SYSTEM_PROMPT,
      `テーマ: ${userTheme}`,
      `出力はJSONのみにしてください。`,
    ]);

    const response = result.response;
    let text = response.text();

    // Clean up markdown block if present
    text = text.replace(/```json\n?|\n?```/g, '').trim();

    const json = JSON.parse(text);

    // Auto-calculation of frames
    let currentFrame = 0;
    json.timeline = json.timeline.map((scene: any, i: number) => {
      const duration = scene.duration_frames || 150;
      const s = {
        ...scene,
        id: i + 1,
        start_frame: currentFrame,
        end_frame: currentFrame + duration,
      };
      currentFrame += duration;
      return s;
    });

    const OUTPUT_FILE = 'src/ai_scenario.json';
    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(json, null, 2));

    console.log(`\n✅ Scenario Generated by Gemini!`);
    console.log(`📂 Saved to: ${OUTPUT_FILE}`);
  } catch (error) {
    console.error('❌ Application Error:', error);
  }
}

main();
